### ISSUE TITLE
Any plans to port it to Linux?

### ISSUE THREAD

**Issue by Klairm** [ahmed605/SparkIV#1]
Hello, do you have any plans to port it for Linux? Or what is needed for open the .rpf files at least? So knowing that i could try to make a rpf editor

**Comment by ahmed605** [comment]
@Klairm porting to Linux will not be hard, but I think it's not most needed as the game itself doesn't run on Linux, but I will look into that thing as soon as I can

**Comment by Klairm** [comment]
> @Klairm porting to Linux will not be hard, but I think it's not most needed as the game itself doesn't run on Linux, but I will look into that thing as soon as I can

Actually, the game works great on Linux, that's where i'm playing it, and tried to run SparkIV under WINE but I can only export , for import it gives an error which is this -> https://pastebin.com/XxDKRc9U

If there could be a way for fixing that error then the program would perfect under Wine without needing of Linux port, but ofc if you can do a port would be better, I know some of C maybe i could try to help to make it possible

Thanks for your time ;) 


EDIT: Got the program working under wine using dotnet48 in wine using winetricks, so the program now doesn't really need a port

**Comment by Klairm** [comment]
Reopen issue just for asking if you could provide some info and documentation you used for creating the program, it runs very good under wine on Linux, but as a personal project I would like to try creating something similar but native for Linux, but I can't find documentation about RPF files and Rage library
