### ISSUE TITLE
Is there a plan to Update this for the Latest GTA Four Steam Update?

### ISSUE THREAD

**Issue by Ekooo08** [ahmed605/SparkIV#2]
Grand Theft Auto 4 used to have GFWL But now Since the Latest Steam Update GFWL is no longer in use. Instead GTA 4 Use Rockstar Social Club in In the Game Instead. But the SparkIV 0.8.1 Says that the EXE for the Latest GTA 4 Update has been Modified so It can't be Usable. So Me and the GTA Community are Asking if there's a Chance for you to Update it to the Latest Steam Version. Thanks for your Time Ahmed.

**Comment by ahmed605** [comment]
can you upload that new exe file to reverse engineer it? Because I don't have the Steam version, oh and also did the app worked with the old/previous steam version because I didn't tried it with the steam version @Ekooo08

**Comment by Ekooo08** [comment]
I Didn’t Really had the Chance to Try the Latest Version of SparkIV on the Last Steam Gta 4 exe (Before the Update) because I Downgraded My Exe to Version 1.0.7.0 for it to work in the SparkIV 0.6.6 Version and the 0.6.6 Version Worked Like a Charm on the 1.0.7.0 Steam Version of Grand Theft Auto 4

**Comment by Ekooo08** [comment]
> can you upload that new exe file to reverse engineer it? Because I don't have the Steam version, oh and also did the app worked with the old/previous steam version because I didn't tried it with the steam version @Ekooo08

I Didn’t Really had the Chance to Try the Latest Version of SparkIV on the Last Steam Gta 4 exe (Before the Update) because I Downgraded My Exe to Version 1.0.7.0 for it to work in the SparkIV 0.6.6 Version and the 0.6.6 Version Worked Like a Charm on the 1.0.7.0 Steam Version of Grand Theft Auto 4

**Comment by ahmed605** [comment]
@Ekooo08 do you know anyone who have the latest exe of the steam version so I can support it?

**Comment by Ekooo08** [comment]
> @Ekooo08 do you know anyone who have the latest exe of the steam version so I can support it?

yup i'll send my GTA4 Steam EXE via Google Drive 
https://drive.google.com/open?id=1WcX9DjMv8uh0eRLuhZ5zJwqbTyL4NSz-

**Comment by ahmed605** [comment]
@Ekooo08 is this the latest version that doesn't work with SparkIV?

**Comment by Ekooo08** [comment]
> @Ekooo08 is this the latest version that doesn't work with SparkIV?

Yup, That’s the Version that Doesn’t Work with SparkIV 0.8.1 Version.

**Comment by ahmed605** [comment]
@Ekooo08 can you try this pre-release version to check if it will work? https://github.com/ahmed605/SparkIV/releases/download/v0.8.51/Beta.zip

**Comment by ahmed605** [comment]
@Ekooo08 did it work?

**Comment by Ekooo08** [comment]
> @Ekooo08 did it work?

 It Worked Like a Charm! Thanks Sir! Btw Can I Post that Github Link on Steam so Everyone Knows there’s a Working SparkIV for the Latest Steam Version? I’ll Credit You and Thanks Again

**Comment by ahmed605** [comment]
@Ekooo08 thanks 👍, yeah you can post/share it in Steam or anything else

**Comment by ahmed605** [comment]
@Ekooo08 BTW can you tell me what is the latest GTA IV steam version number (e.g 1.0.8.0)?

**Comment by Ekooo08** [comment]
> @Ekooo08 BTW can you tell me what is the latest GTA IV steam version number (e.g 1.0.8.0)?

Yeah Sure, It’s not the 1.0.8.0 Anymore It’s the Latest Version 1.2.0.32 They Also Included the Episodes from Liberty City so It Isn’t a Standalone Game Anymore.

**Comment by ahmed605** [comment]
@Ekooo08 really!, so can you upload the EFLC exe also to support it too?

**Comment by Ekooo08** [comment]
> @Ekooo08 really!, so can you upload the EFLC exe also to support it too?

Well It Doesn’t have an EFLC EXE Unfortunately. Because EFLC is Included in the Gta 4 exe. I Also Tested SparkIV on the EFLC Files (Included in the GTA 4 Files) and It’s Also Working like a Charm

**Comment by ahmed605** [comment]
@Ekooo08 Hi, can you help me in something? (as you are the only one I know who have the complete edition of the game), I need to add support to the complete edition in .NET ScriptHook but I don't have this version so I need you to check some values in the game so I can the support into it, can you help me in that?

**Comment by Ekooo08** [comment]
> @Ekooo08 Hi, can you help me in something? (as you are the only one I know who have the complete edition of the game), I need to add support to the complete edition in .NET ScriptHook but I don't have this version so I need you to check some values in the game so I can the support into it, can you help me in that?

oh shoot. i don't really know how to Check the Values on the game. but maybe i can look to it. just show me how

**Comment by ahmed605** [comment]
@Ekooo08 Don't worry I will guide you 👍, BTW do you have Discord or Twitter? (because it's easier and better to chat on them)
