### ISSUE TITLE
Does this version work on GTA V ?

### ISSUE THREAD

**Issue by amrshaheen61** [ahmed605/SparkIV#6]
Does this version work on GTA V ?

**Comment by ahmed605** [comment]
Nope, GTA V has a different rage version and totally different encryption method 

Edit: I recommend you to use OpenIV (closed source) or CodeWalker (open source) instead

**Comment by amrshaheen61** [comment]
@ahmed605 
Please, I want to know. functions names for opening the rpf file and using an external dll file

**Comment by amrshaheen61** [comment]
@ahmed605 
Thank you
