### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by BrynnaDaRosa** [ahmed605/SparkIV#7]
Suddenly getting this error.

![Screenshot_2](https://user-images.githubusercontent.com/73003230/102551322-49f08d00-408d-11eb-974c-ebbdcc95df6d.png)

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at RageLib.Common.KeyUtil.FindGameDirectory() in C:\projects\sparkiv\SRC\RageLib\Common\KeyUtil.cs:line 82
>    at SparkIV.MainForm.LoadGameDirectory(KeyUtil keyUtil, String gameName) in C:\projects\sparkiv\SRC\SparkIV\MainForm.cs:line 399
>    at SparkIV.MainForm.toolStripGTAIV_Click(Object sender, EventArgs e) in C:\projects\sparkiv\SRC\SparkIV\MainForm.cs:line 468
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> SparkIV
>     Assembly Version: 0.8.56.0
>     Win32 Version: 0.8.56.0
>     CodeBase: file:///C:/Users/Niko/Downloads/Beta%20(1)/SparkIV.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> Ookii.Dialogs
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///C:/Users/Niko/Downloads/Beta%20(1)/Ookii.Dialogs.DLL
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> RageLib.Common
>     Assembly Version: 0.6.2.0
>     Win32 Version: 0.6.2.0
>     CodeBase: file:///C:/Users/Niko/Downloads/Beta%20(1)/RageLib.Common.DLL
> ----------------------------------------
> RageLib.FileSystem
>     Assembly Version: 0.6.2.0
>     Win32 Version: 0.6.2.0
>     CodeBase: file:///C:/Users/Niko/Downloads/Beta%20(1)/RageLib.FileSystem.DLL
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
>

**Comment by BrynnaDaRosa** [comment]
Still having this issue :(

**Comment by ahmed605** [comment]
@BrynnaDaRosa Oh sorry I just saw this issue now,
Unfortunately I don't have much time to work on this project but I will look into your issue as soon as possible 

For a temporary fix:
- GTA IV
  - 32-bit system:
    Open registry and add key called `InstallFolder` to this path `SOFTWARE\Rockstar Games\Grand Theft Auto IV` and set it to your GTA IV game folder (that contains the game exe file).
  - 64-bit system:
    Open registry and add key called `InstallFolder` to this path `SOFTWARE\Wow6432Node\Rockstar Games\Grand Theft Auto IV` and set it to your GTA IV game folder (that contains the game exe file).
- GTA EFLC
  - 32-bit system:
    Open registry and add key called `InstallFolder` to this path `SOFTWARE\Rockstar Games\EFLC` and set it to your GTA EFLC game folder (that contains the game exe file).
  - 64-bit system:
    Open registry and add key called `InstallFolder` to this path `SOFTWARE\Wow6432Node\Rockstar Games\EFLC` and set it to your GTA EFLC game folder (that contains the game exe file).

**Comment by BrynnaDaRosa** [comment]
Thank you! I have no idea what those instructions mean, but thank you!

**Comment by BrynnaDaRosa** [comment]
Any news?

**Comment by BrynnaDaRosa** [comment]
Still getting this error. I've tried everything, running it as administrator, trying to follow whatever it was that you showed me, to no avail.

**Comment by ahmed605** [comment]
@BrynnaDaRosa Hi, sorry for being very late
Can you try if this fixes your issue?
https://github.com/ahmed605/SparkIV/releases/download/v0.8.60/Beta.zip

**Comment by BrynnaDaRosa** [comment]
YES!!! Thank you so much!!! You might not think so but SparkIV is still very valuable in GTA IV modding. Right now there is ZERO way to export models from GTA IV without 3DS Max, and with GIMS IV becoming more and more outdated and incompatible with new versions of Max, Even though exporting to smd with SparkIV breaks vertex groups, its still much better than nothing.

**Comment by ahmed605** [comment]
No problem, glad it worked!
